### PR TITLE
Develop

### LINKED ISSUE #76: Error after install kaya-cli as npm package
Hello,

I'm using Node v11.10.1 installed by nvm. I have installed kaya-cli `npm install -g kaya-cli`. 

When I run `kaya-cli` from terminal, I got the error.

```
kaya-cli
internal/modules/cjs/loader.js:615
    throw err;
    ^

Error: Cannot find module 'tslib'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:613:15)
    at Function.Module._load (internal/modules/cjs/loader.js:539:25)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/developers/.nvm/versions/node/v11.10.1/lib/node_modules/kaya-cli/node_modules/@zilliqa-js/util/dist/index.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
```

Can someone help me with this issue? 

**NOTE**: 

@edisonljh I think I found the issue, you need to add `tslib` as dev dependency to the package.json. I tried and it works

I can start the server by `kaya-cli`

```
 kaya-cli
ZILLIQA KAYA RPC SERVER (ver: 0.2.6)
Server listening on 127.0.0.1:4200
Running from local interpreter
================================================================================
Available Accounts
================================================================================
(1) f949cd77cd1ad980492ba3f7afc208c969dede62    (1000000 ZILs)  (Nonce: 0)
(2) 1ab8b643ec6f62ee9dfcc8b2e222f809a5a7258a    (1000000 ZILs)  (Nonce: 0)
(3) d165816d56a9b6cb4552db468cb3121440967953    (1000000 ZILs)  (Nonce: 0)
(4) 5aaa209d65a527170d018902d420daf13cd7ea08    (1000000 ZILs)  (Nonce: 0)
(5) 7eb6c1d20542b1452f47323112fe72838d0070a9    (1000000 ZILs)  (Nonce: 0)
(6) 5dd43414d6aa2d1370598a0ede5775b211fb2023    (1000000 ZILs)  (Nonce: 0)
(7) 541cd8739bb6948ff9116fbbeeaf46d992121e71    (1000000 ZILs)  (Nonce: 0)
(8) a78ca865d1bbaf2af472d990f004369ea150d9e9    (1000000 ZILs)  (Nonce: 0)
(9) 96755f2f9fc8499319fe68a5d07eb746a70baed9    (1000000 ZILs)  (Nonce: 0)
(10) 5c4068f17d0dd6304c2cf5b3d68db769021352ae   (1000000 ZILs)  (Nonce: 0)

 Private Keys
================================================================================
(1) 7bf8089b7a524e3f4ef507249d8d0de3447920a13db96d1e55098eaef132497a
(2) d43ad75a3f9d4482a7a6c752d4f013aecead26772aac6ebe47904a9479adaf29
(3) eb63c6f310b7da3f2cfbc701da0db24d95c40b966abc84838e039af4d08cf65f
(4) 33d5b71040f2da508b74dfa43046d8a3d89d94c3186e23e7ad4aea8123e6a2ef
(5) fb2b984bef959ae7cc451a190a26c49ce7e06203faf64302d73cd931c3f434a6
(6) cc0ffb6ce56f46ccd60e5fb7630e17017bd8552886d1e3c60dff31857f931c77
(7) 28f7d7ea73c8d3d8629755ee05e2d5b17aa8b11951cc880bca3986ed53037f31
(8) ff76411c725d5f8dfe7595b9b48de039bb21bda2367b731fc87bf6dd11bdbcbb
(9) dbfbd90973003a62fde579564b81fe62f58d1a3f7b4ebde1bb3b43ed8fbc680e
(10) 05acfdc0259303d35f8f61f55b181ad4cdcd2b547a277f116ac637d8f35ad8f1
================================================================================
```

### PR DESCRIPTION
**Pull request by edisonljh**
## Description
Fix installation issue due to missing `tslib` package:  #76 
Fix port issues with `-p` #79

### CODE REVIEW

File: src/server.js [hunk 1]
```diff
@@ -17,15 +17,27 @@
 */
 
 const config = require('./config');
+const yargs = require('yargs');
+const initArgv = require('./argv');
+
+let server_port;
```
Comment (noelyoo) [inline src/server.js]: how about `server_port` -> `serverPort`?
https://eslint.org/docs/developer-guide/code-conventions#naming
