### PR TITLE
Fix/gaslimit

### LINKED ISSUE #36: Gas Limit Option not enabled
The latest scilla binary has an additional flag `--gaslimit` that is not being handled by Kaya RPC now.

### PR DESCRIPTION
**Pull request by edisonljh**
## Description
- Fixes #36 
- GasLimit is now correctly specified in the command. The actual gas consumed according to the interpreter is now deducted from the user's balance
- This PR will be incompatible with the older versions of scilla-runner. Please update your scilla runner to the latest version

## Review Suggestion
- `npm test` and manual testing

### Implementation
- [x] **ready for review**

### CODE REVIEW

File: logic.js [hunk 1]
```diff
@@ -150,24 +150,26 @@ module.exports = {
...
           payload,
           contractAddr,
           dir,
           currentBNum,
           payload.gasLimit
         )
         // Deduct funds
-        walletCtrl.deductFunds(senderAddress, payload.amount + payload.gasLimit)
+        let nextAddr = responseData.nextAddress;
+        let gasConsumed = payload.gasLimit - responseData.gasRemaining;
```
Comment (iantanwx) [inline logic.js]: Currently, pending confirmation from @AmritKumar, the I have fixed gas price at the ratio of 1:1 gas to zil. I think it is worth assigning a dummy `gasPrice`, such that the call will become `walletCtrl.deductFunds(senderAddress, payload.amount + gasConsumed * gasPrice)` to avoid having to refactor when gas price becomes a factor on the main net.
